# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'TuIdentidadSDK_Example' do
  use_frameworks!
  
  pod 'TuIdentidadSDK', :path => '../'
  pod 'TuIdentidadSDK/AddressKit', :path => '../'
  
  target 'TuIdentidadSDK_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
